"""fix: made some members column nullable

Revision ID: 02d7855f450e
Revises: ff77fae6fdf4
Create Date: 2024-09-06 16:46:23.252271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02d7855f450e'
down_revision = 'ff77fae6fdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('setup_completed', sa.Boolean(), nullable=False))
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('employment_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('occupation',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('marital_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('marital_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('occupation',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('employment_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('setup_completed')
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
