"""feat: included interest amount and total amount

Revision ID: 327f6d3b805a
Revises: f72ff075a3ea
Create Date: 2024-09-12 16:42:08.145415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327f6d3b805a'
down_revision = 'f72ff075a3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_amount',
                            sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(
            sa.Column('total_amount', sa.Integer(), nullable=False, server_default='5'))
        # batch_op.alter_column('amount',
        #                       existing_type=sa.VARCHAR(),
        #                       type_=sa.Integer(),
        #                       existing_nullable=False)
        batch_op.execute(
            'ALTER TABLE loans ALTER COLUMN amount TYPE INTEGER USING amount::integer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('amount',
                              existing_type=sa.Integer(),
                              type_=sa.VARCHAR(),
                              existing_nullable=False)
        batch_op.drop_column('total_amount')
        batch_op.drop_column('interest_amount')

    # ### end Alembic commands ###
