"""fix: updated organisation account

Revision ID: 48b073218321
Revises: bc63e47c8994
Create Date: 2024-09-14 05:53:04.065244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48b073218321'
down_revision = 'bc63e47c8994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('bank_code', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('organisation', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organisation'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('organisational_accounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisational_accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bank_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('organisation', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisation'], ['organisations.id'], name='organisational_accounts_organisation_fkey'),
    sa.PrimaryKeyConstraint('id', name='organisational_accounts_pkey'),
    sa.UniqueConstraint('id', name='organisational_accounts_id_key')
    )
    op.drop_table('organisation_accounts')
    # ### end Alembic commands ###
