"""fix: remove two column from organisational role

Revision ID: e0f8d0484ca1
Revises: 02d7855f450e
Create Date: 2024-09-06 22:34:09.312343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0f8d0484ca1'
down_revision = '02d7855f450e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisational_roles', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisational_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
