"""feat: update loan interest datatype

Revision ID: f72ff075a3ea
Revises: e0f8d0484ca1
Create Date: 2024-09-12 16:28:24.075893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72ff075a3ea'
down_revision = 'e0f8d0484ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        # batch_op.alter_column('interest_at',
        #                       existing_type=sa.TEXT(),
        #                       type_=sa.Float(),
        #                       existing_nullable=False)
        batch_op.execute(
            'ALTER TABLE loans ALTER COLUMN interest_at TYPE FLOAT USING interest_at::double precision')
        batch_op.drop_column('image_id')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(),
                            autoincrement=False, nullable=True))
        batch_op.add_column(
            sa.Column('image_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('interest_at',
                              existing_type=sa.Float(),
                              type_=sa.TEXT(),
                              existing_nullable=False)

    # ### end Alembic commands ###
