"""feat: changed org. username to shortname

Revision ID: fd52d5b115cb
Revises: 423dfae21186
Create Date: 2024-09-24 13:45:40.850315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd52d5b115cb'
down_revision = '423dfae21186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(), nullable=False, server_default="shortname"))
        batch_op.drop_constraint('organisations_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('organisations_username_key', ['username'])
        batch_op.drop_column('short_name')

    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
