"""fix: organisations.setup_completed

Revision ID: ff77fae6fdf4
Revises: 2d3d8144e642
Create Date: 2024-09-06 14:55:42.267409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff77fae6fdf4'
down_revision = '2d3d8144e642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_completed', sa.Boolean(), nullable=False))
        batch_op.alter_column('date_of_establishment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('date_of_establishment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('setup_completed')

    # ### end Alembic commands ###
